"""Configurando

Revision ID: 8f0d08729151
Revises: 
Create Date: 2025-06-01 16:09:21.037516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0d08729151'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('endereco_num_residencia', sa.String(), nullable=False),
    sa.Column('endereco_rua', sa.String(), nullable=False),
    sa.Column('endereco_bairro', sa.String(), nullable=False),
    sa.Column('endereco_cidade', sa.String(), nullable=False),
    sa.Column('endereco_complemento', sa.String(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cod_promocional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('combo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('imagem_link', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('popular', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('imagem_link', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('popular', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Float(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('status_comanda', sa.String(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_entrega', sa.String(), nullable=False),
    sa.Column('metodo_pagamento', sa.String(), nullable=False),
    sa.Column('valor_a_pagar', sa.Float(), nullable=False),
    sa.Column('status_pagamento', sa.String(), nullable=False),
    sa.Column('troco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_produto',
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combo_id'], ['combo.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('combo_id', 'produto_id')
    )
    op.create_table('pedido_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.Column('id_combo', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id'], ),
    sa.ForeignKeyConstraint(['id_combo'], ['combo.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_item')
    op.drop_table('combo_produto')
    op.drop_table('comanda')
    op.drop_table('produto')
    op.drop_table('combo')
    op.drop_table('cod_promocional')
    op.drop_table('cliente')
    # ### end Alembic commands ###
